using System.ComponentModel.DataAnnotations;

namespace TicketManager.Web.Models;

/// <summary>
/// Represents a follow-up note recorded on an internal ticket.
/// </summary>
public class TicketComment
{
    /// <summary>
    /// Unique identifier generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Identifier of the ticket that owns this comment.
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// Ticket that owns this comment.
    /// </summary>
    public Ticket? Ticket { get; set; }

    /// <summary>
    /// Name supplied by the person adding the comment.
    /// </summary>
    [Required(ErrorMessage = "O autor e obrigatorio.")]
    [StringLength(80)]
    [Display(Name = "Autor")]
    public string AuthorName { get; set; } = string.Empty;

    /// <summary>
    /// Follow-up text recorded for the ticket.
    /// </summary>
    [Required(ErrorMessage = "O comentario e obrigatorio.")]
    [StringLength(1000)]
    [Display(Name = "Comentario")]
    public string Body { get; set; } = string.Empty;

    /// <summary>
    /// UTC date and time when the comment was created.
    /// </summary>
    [Display(Name = "Criado em")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
