using System.ComponentModel.DataAnnotations;

namespace TicketManager.Web.Models;

/// <summary>
/// Represents a chronological note added to a ticket during follow-up.
/// </summary>
public class TicketComment : IValidatableObject
{
    /// <summary>
    /// Unique identifier generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Identifier of the ticket this comment belongs to.
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// Free-text author name entered by the user.
    /// </summary>
    [Required(ErrorMessage = "O autor é obrigatório.")]
    [StringLength(80, MinimumLength = 2, ErrorMessage = "O autor deve ter entre 2 e 80 caracteres.")]
    [Display(Name = "Autor")]
    public string AuthorName { get; set; } = string.Empty;

    /// <summary>
    /// Comment text that describes the follow-up update.
    /// </summary>
    [Required(ErrorMessage = "O comentário é obrigatório.")]
    [StringLength(1000, MinimumLength = 1, ErrorMessage = "O comentário deve ter entre 1 e 1000 caracteres.")]
    [Display(Name = "Comentário")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// UTC date and time when the comment was created.
    /// </summary>
    [Display(Name = "Criado em")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Ticket associated with this comment.
    /// </summary>
    public Ticket? Ticket { get; set; }

    /// <inheritdoc />
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (!string.IsNullOrEmpty(Content) && string.IsNullOrWhiteSpace(Content))
        {
            yield return new ValidationResult("O comentário não pode conter apenas espaços.", new[] { nameof(Content) });
        }
    }
}