using System.ComponentModel.DataAnnotations;

namespace TicketManager.Web.Models;

/// <summary>
/// Represents an internal support request managed by the application.
/// </summary>
/// <remarks>
/// Tickets are created by users through the MVC interface and move through a
/// simple status workflow while they are being followed by the internal team.
/// </remarks>
public class Ticket
{
    /// <summary>
    /// Unique identifier generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Short title that summarizes the internal request.
    /// </summary>
    [Required(ErrorMessage = "O título é obrigatório.")]
    [StringLength(120)]
    [Display(Name = "Título")]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed explanation of the request or problem reported by the user.
    /// </summary>
    [Required(ErrorMessage = "A descrição é obrigatória.")]
    [StringLength(2000)]
    [Display(Name = "Descrição")]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Business priority assigned to the ticket.
    /// </summary>
    [Required(ErrorMessage = "A prioridade é obrigatória.")]
    [Display(Name = "Prioridade")]
    public TicketPriority Priority { get; set; } = TicketPriority.Medium;

    /// <summary>
    /// Current workflow state of the ticket.
    /// </summary>
    [Required(ErrorMessage = "O estado é obrigatório.")]
    [Display(Name = "Estado")]
    public TicketStatus Status { get; set; } = TicketStatus.Open;

    /// <summary>
    /// UTC date and time when the ticket was created.
    /// </summary>
    [Display(Name = "Criado em")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Chronological comments added during ticket follow-up.
    /// </summary>
    public ICollection<TicketComment> Comments { get; set; } = new List<TicketComment>();
}
